### ISSUE TITLE
FeatureComplete: handle symlinks 

### ISSUE THREAD

**Issue by mcharsley** [uutils/findutils#12]
This involves handling -H, -L and finishing find::matchers::type_matcher.

Take a look at https://github.com/BurntSushi/walkdir/blob/master/examples/walkdir.rs for hints on how to handle -L with walkdir and https://github.com/BurntSushi/walkdir/blob/master/src/tests.rs on how to test interaction with symlinks on both unix and windows machines

**Comment by tavianator** [comment]
Note that the current behaviour seems to be `-H` (follow top-level links), not `-P` (never follow links):

```
$ ln -s / link
$ find link
link
$ ./target/debug/find link
link
link/var
link/var/cache
link/var/cache/pacman
link/var/cache/pacman/pkg
...
```
