### ISSUE TITLE
shows the differences with the other testsuites like in coreutils

### ISSUE THREAD

**Issue by sylvestre** [uutils/findutils#128]
In coreutils, we have a great way to show progress / regression compared to the GNU testsuite

For example:
https://github.com/uutils/coreutils/runs/4833285375?check_suite_focus=true
![image](https://user-images.githubusercontent.com/733326/149680179-933ea77a-c21f-436e-bd53-f1ffef787640.png)

Implementation:
https://github.com/uutils/coreutils/blob/main/.github/workflows/GnuTests.yml

It would be great to have this here too.

**Comment by sylvestre** [comment]
@refi64 would be interested in implementing this? :)
thanks

**Comment by refi64** [comment]
Hmm sounds interesting, presumably this would be running against the GNU and BFS test suites?

**Comment by sylvestre** [comment]
yeah :)
(would be easier to review your patches :)
