### ISSUE TITLE
About 0.4.1 release

### ISSUE THREAD

**Issue by chenrui333** [uutils/findutils#261]
👋 while [upgrading rust to 1.71.0](https://github.com/Homebrew/homebrew-core/pull/136514), we found that uutils-findutils 0.4.1 checksum got changed, raise this issue to confirm if there was a re-reg for the 0.4.1 release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137183

**Comment by tertsdiepraam** [comment]
We haven't changed the release as far as I know (or have we @sylvestre?). What are you checksumming exactly?

**Comment by sylvestre** [comment]
dunno :(

**Comment by chenrui333** [comment]
> We haven't changed the release as far as I know (or have we @sylvestre?). What are you checksumming exactly?

just checking the integrity for the artifacts.

**Comment by chenrui333** [comment]
This is what I found with the re-tagging situation, 0.4.1, first applied to 6a034e28e8261fc7f42b9224f77df8dced7e6cb3, and this is [the first 0.4.1 action run](https://github.com/uutils/findutils/actions/runs/5522683545)

![image](https://github.com/uutils/findutils/assets/1580956/9c37d149-30ba-4d60-a1c1-e3acf3f53473)


But somehow, there was a re-tag applied to 13b4ae4d45c4c4c60be66e566a0c932f7503a9d2, and this is the second tag run, https://github.com/uutils/findutils/actions/runs/5531228071

![image](https://github.com/uutils/findutils/assets/1580956/68488e08-736e-4a29-a6f5-c170b26f47f5)

There is nothing with that, but just want to follow the process in here.

**Comment by sylvestre** [comment]
yeah, this is probably me doing stupid things. let me do a new release

**Comment by chenrui333** [comment]
totally no worries, just to raise the issue for some awareness (and maybe some automation opportunity :) )

**Comment by chenrui333** [comment]
oh, just your new release change, appreciate it!!
