### ISSUE TITLE
Release binaries, like you do for uutils-coreutils

### ISSUE THREAD

**Issue by dflock** [uutils/findutils#273]
I would be great in uutils-findutils released binaries, like uutils-coreutils does! This makes it much easier for people to make scoop manifests etc... to install the findutils.

**Comment by tertsdiepraam** [comment]
Good idea! Would you like to work on this feature? We can probably copy-paste some steps for this from https://github.com/uutils/coreutils/blob/main/.github/workflows/CICD.yml.

**Comment by sylvestre** [comment]
we are now:
https://github.com/uutils/findutils/releases/tag/0.5.0

**Comment by YDX-2147483647** [comment]
> much easier for people to make scoop manifests etc... to install the findutils.

And here is one: https://github.com/YDX-2147483647/scoop-bucket/blob/main/bucket/uutils-findutils.json ([permalink](https://github.com/YDX-2147483647/scoop-bucket/blob/b5225a951891eb85b6f2160f3e123b20036a966f/bucket/uutils-findutils.json))

**Comment by sylvestre** [comment]
maybe do it for:
https://github.com/uutils/diffutils/
too ? ;)
thanks

**Comment by YDX-2147483647** [comment]
Done. https://github.com/YDX-2147483647/scoop-bucket/blob/main/bucket/uutils-diffutils.json ([permalink](https://github.com/YDX-2147483647/scoop-bucket/blob/f1c21c51b4feb1dfb5b0d6ac1bdaf4bd752b7325/bucket/uutils-diffutils.json))

```json
{
    "version": "0.4.0",
    "description": "Rust implementation of GNU diffutils (binaries compiled with MSVC)",
    "homepage": "https://uutils.github.io/diffutils/",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/uutils/diffutils/releases/download/v0.4.0/diffutils-x86_64-pc-windows-msvc.zip",
            "hash": "be114bcf69793b991a4099d289036c301491a9a74c7803aa1b325edc2a1d5b13"
        }
    },
    "bin": [
        "diffutils.exe"
    ],
    "checkver": {
        "github": "https://github.com/uutils/diffutils"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/uutils/diffutils/releases/download/v$version/diffutils-x86_64-pc-windows-msvc.zip"
            }
        }
    }
}
```

However please note that this is my personal scoop bucket.
It is OK for anyone to use my personal bucket (GitHub pays for it), but creating an official uutils bucket might be better. (A scoop bucket is just a GitHub repo with CI.)
And if someday our findutils and diffutils meet [the main bucket criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket), those manifests can be taken as a startup.
