### ISSUE TITLE
-execdir doesn't chdir for the root

### ISSUE THREAD

**Issue by tavianator** [uutils/findutils#28]
```
$ ./target/debug/find / -maxdepth 0 -execdir pwd \;
/home/tavianator/code/uutils/findutils
$ find / -maxdepth 0 -execdir pwd \;
/
```

**Comment by mcharsley** [comment]
Weirdly, my copy of gnu find behaves the same as the rust version:

$ cd /tmp
$ /usr/bin/find / -maxdepth 0 -execdir pwd \;
/tmp
$ find --version
find (GNU findutils) 4.4.2
Copyright (C) 2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Built using GNU gnulib version e5573b1bad88bfabcda181b9e0125fb0c52b7d3b
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS() CBO(level=0)

**Comment by tavianator** [comment]
Indeed, but your copy of GNU find is 10 years old :)
