### ISSUE TITLE
Empty brackets accepted

### ISSUE THREAD

**Issue by tavianator** [uutils/findutils#29]
I assume this isn't an intentional extension:

```
$ ./target/debug/find \( \)
.
./.git
...
```

**Comment by mcharsley** [comment]
I worked on the basis "when in doubt, do what GNU's find does". I grant you that it's fairly useless behaviour, but 
 - it matches GNU find
 - it's harmless enough

**Comment by tavianator** [comment]
But

```
$ find \( \)
find: invalid expression; empty parentheses are not allowed.
```

Anyway, I agree it's relatively harmless to allow it.

**Comment by mcharsley** [comment]
My mistake. I tried

find /tmp \(\)

and killed the process before I saw "find: `()': No such file or directory"

putting a space between the brackets does indeed give an error. That should
be simple enough to fix.

thanks for the bug reports by the way. Nice to see someone's looking at the
code :-).

**Comment by hanbings** [comment]
Hello, I tried to solve it by adding a special judgment to the Matcher of uutils/findutils, and it seems to work. I've submitted a PR. :)
