### ISSUE TITLE
xargs: stdin should not be merged before replacing

### ISSUE THREAD

**Issue by YDX-2147483647** [uutils/findutils#362]
Given the following stdin,

```
abc
def
g
```

`xargs -i echo [{}]` should give

```
[abc]
[def]
[g]
```

instead of `[abc def g]`.

<summary>Test using python</summary>

(Ubuntu)

```python
>>> from subprocess import run

# xargs 0.5.0 from uutils
>>> run(['./xargs', '-i', 'echo', '[{}]'], capture_output=True, input=b"abc\ndef\ng").stdout
b'[abc def g]\n'

# xargs 4.8.0 from GNU
>>> run(['/usr/bin/xargs', '-i', 'echo', '[{}]'], capture_output=True, input=b"abc\ndef\ng").stdout
b'[abc]\n[def]\n[g]\n'
```

<summary>Test using shell</summary>

(MSYS2 on Windows)

```shell
# xargs 0.5.0 from uutils
$ printf 'abc\ndef\ng' | ./xargs -i echo [{}]
[abc def g]

# xargs 4.9.0 from GNU
$ printf 'abc\ndef\ng' | xargs -i echo [{}]
[abc]
[def]
[g]
```

**Platform**: unknown-linux-gnu, pc-windows-msvc, other not tested.

## Relavant codes

https://github.com/uutils/findutils/blob/baa09baf47992a074538ed0e4bb3c4e952f37111/src/xargs/mod.rs#L407-L435

There's no test on this behaviour.

https://github.com/uutils/findutils/blob/baa09baf47992a074538ed0e4bb3c4e952f37111/tests/xargs_tests.rs#L429-L430

Relates-to: #323

**Comment by sylvestre** [comment]
I am curious why you are sharing a python example ? :)

would you like to try to provide a fix?
thanks

**Comment by YDX-2147483647** [comment]
> why you are sharing a python example

I thought it was caused by CR/LF or shells, so I want to feed bytes to the executable directly. AFAIK, python is the easiest way.

> would you like to try to provide a fix?

I'd like to do so! But I cannot guarantee when, maybe in a month?

**Comment by YDX-2147483647** [comment]
I've inspected it deeper. The issue is harder than I thought. The command is always executed once in current implementation, but it needs to be executed multiple times if `-i/--replace` or `-I` is given.

---

The following is to be appended to `tests/xargs_tests.rs`.

```rust
    // Multiple lines
    Command::cargo_bin("xargs")
        .expect("found binary")
        .args(["-i=_", "echo", "[_]"])
        .write_stdin("abc\ndef\ng")
        .assert()
        .success()
        .stderr(predicate::str::is_empty())
        .stdout(predicate::str::diff("[abc]\n[def]\n[g]\n"));

    Command::cargo_bin("xargs")
        .expect("found binary")
        .args(["-i", "echo", "{} {} foo"])
        .write_stdin("bar\nbaz")
        .assert()
        .stdout(predicate::str::diff("bar bar foo\nbaz baz foo"));
```

**Comment by YDX-2147483647** [comment]
## Workaround

Pass `-n 1` or `--max-args 1`.

```shell
$ printf 'abc\ndef\ng' | xargs -I _ -n 1 echo [_]
[abc]
[def]
[g]
```

[Conflicting xargs options (GNU Findutils 4.9.0)](https://www.gnu.org/software/findutils/manual/html_node/find_html/Conflicting-xargs-options.html):

> The options ‘`--max-lines`’ (‘`-L`’, ‘`-l`’), ‘--replace’ (‘`-I`’, ‘`-i`’) and ‘`--max-args`’ (‘`-n`’) are mutually exclusive.
>
> The exception to this rule is that the special _max-args_ value _1_ is ignored after the ‘`--replace`’ option and its short-option aliases ‘`-I`’ and ‘`-i`’, because it would not actually conflict.

**Comment by YDX-2147483647** [comment]
Hi! I've fixed the issue in normal cases, but if conflict options are given, things get complicated. (I need to make `options` mutable.)

Currently, we throw a warning and take the last option.

https://github.com/uutils/findutils/blob/baa09baf47992a074538ed0e4bb3c4e952f37111/src/xargs/mod.rs#L930-L933

Should I follow this behaviour? Or may I use [`Arg::conflicts_with` in clap](https://docs.rs/clap/4.5.4/clap/struct.Arg.html#method.conflicts_with) and throw an error?
