### ISSUE TITLE
Centralize handling of `uucore::error::set_exit_code()` calls.

### ISSUE THREAD

**Issue by hanbings** [uutils/findutils#440]
refer: https://github.com/uutils/findutils/pull/421#discussion_r1705629746

> This could be a method on `MatcherIO`, and then you wouldn't need to unset it in the tests

Note: Currently we have two `uucore::error::set_exit_code()` in the entire find code.

**Comment by tavianator** [comment]
This is done in https://github.com/uutils/findutils/pull/436/commits/e73334f95a788a5be13570d899fc584dc3b3856c
