### ISSUE TITLE
different behavior with printf %A

### ISSUE THREAD

**Issue by sylvestre** [uutils/findutils#451]
```
$ touch a
# with our implementation:
$ find a -printf " %A+\n"          
 2024-09-11T10:34:33.361901073+00:00

# With GNU:
$ find a -printf " %A+\n"
 2024-09-11+12:34:33.3619010730
```

**Comment by sylvestre** [comment]
@hanbings rings a bell? thanks

**Comment by hanbings** [comment]
> @hanbings rings a bell? thanks

Looks like it's related to https://github.com/uutils/findutils/blob/main/src/find/matchers/printf.rs#L38, let me investigate a little more closely. :)
