### ISSUE TITLE
Double negation is the same as single negation

### ISSUE THREAD

**Issue by tavianator** [uutils/findutils#51]
```
$ find \! \! -name find
./src/find
./target/debug/find
$ ./target/debug/find \! \! -name find
.
./.git
./.git/branches
./.git/hooks
./.git/hooks/applypatch-msg.sample
...
```

[Here](https://github.com/uutils/findutils/blob/master/src/find/matchers/mod.rs#L293) when detecting a `-not`/`!` it does `invert_next_matcher = true`, but maybe it should be something more like `invert_next_matcher = !invert_next_matcher`?

**Comment by cnd** [comment]
closed?

**Comment by Arcterus** [comment]
This should be fixed now.
